### PR TITLE
some small fixes

### PR DESCRIPTION
**Pull request by Dorbedo**
**When merged this pull request will:**
- fix travis
- add new checks
- fixing bugs
- optimize things

### CODE REVIEW

**Comment by dedmen** [comment]
>makes no sense to evaluate this at every call
Very nice.. Actually never thought of that.

**Comment by Dorbedo** [comment]
You could work with `__EVAL` if you want to be more flexible.

**Comment by dedmen** [comment]
Why remove the travis integration?

**Comment by Dorbedo** [comment]
I thought we don't have travis?

**Comment by dedmen** [comment]
https://github.com/michail-nikolaev/task-force-arma-3-radio/pull/1423/files#diff-354f30a63fb0907d4ad57269548329e3L3
Just not used yet. Because ^

**Comment by Dorbedo** [comment]
if you want to use it, here you go :-)

**Comment by Dorbedo** [comment]
Let's merge.

**Pull request merged**
