### PR TITLE
Fix the loss of radio v2

### PR DESCRIPTION
**Pull request by MrDell61**
If the player inventory is full, then when change the radio, the old one is deleted. So most likely easier.

### CODE REVIEW

**Comment by dedmen** [comment]
afaik assignItem won't do anything if the slot is already occupied.
What I was thinking of was 
```
private _couldAdd = canAdd _old;
TFAR_currentUnit unassignItem _old;
TFAR_currentUnit assignItem _this;
if (!_couldAdd) then {TFAR_currentUnit addItem _old;}; //We couldn't put it into inventory before but now we have space for sure.
```

**Comment by MrDell61** [comment]
No, If there is no space in inventory the item simply disappears. https://community.bistudio.com/wiki/unassignItem
But if you want, you can do as you propose.

**Comment by dedmen** [comment]
But in your example you were always adding the item.. even if unassign item might have succeeded. Causing duplicates.

**Comment by MrDell61** [comment]
I did as you asked.

**Comment by dedmen** [comment]
Looks correct for you too? right?

**Comment by MrDell61** [comment]
With this use, they work the same way.

**Comment by dedmen** [comment]
https://community.bistudio.com/wiki/canAdd syntax was wrong. object was missing

**Comment by MrDell61** [comment]
Sorry, I did not check

**Comment by shukari** [comment]
is not https://community.bistudio.com/wiki/linkItem better?

**Comment by MrDell61** [comment]
> is not https://community.bistudio.com/wiki/linkItem better?

> But in your example you were always adding the item.. even if unassign item might have succeeded. Causing duplicates.

**Comment by dedmen** [comment]
No. Because the item is moved from Inventory to the slot. linkItem would create a duplicate.

**Pull request merged**
