### PR TITLE
French translation 1.0

### PR DESCRIPTION
**Pull request by NorXAengell**

### CODE REVIEW

**Comment by NorXAengell** [comment]
Don't know if it's good or not...But i really don't like the way git work -_-...I never know if i make a mistake or not...

**Comment by dedmen** [comment]
Why did you merge master into 1.0 ?! 
No worries. I can fix this if `Edits from maintainers` is enabled.
What? Travis build failed? We don't even use Travis.

**Comment by dedmen** [comment]
the stringtable thing might be fine.. But you add files that shouldn't even exist anymore.. 
I may just take your stringtable and integrate it...

**Comment by NorXAengell** [comment]
Yep sorry for this and thx :).

**Comment by dedmen** [comment]
Merged in #1322. Thanks @Dorbedo

**Pull request closed without merging**
