### PR TITLE
Minor improvements for the German translation

### PR DESCRIPTION
**Pull request by Macusercom**
Just minor improvements and corrected grammar

### CODE REVIEW

**Comment by michail-nikolaev** [comment]
Thanks a lot!

**Comment by michail-nikolaev** [comment]
Add you to README thanks section :)

**Comment by Macusercom** [comment]
@michail-nikolaev You're welcome! I love TFAR and stumbled upon some mistakes all the time. Luckily this is no closed source so I though I could improve it a little bit like 0,0001% xP

Thank you! I've added my name to the 3 READMEs. Sorry for the 3 pull requests, I edited it directly and it seems that GitHub creates a new request for every small edit (or maybe I'm just stupid) xD

**Comment by michail-nikolaev** [comment]
Thanks a lot!

**Pull request merged**
