### PR TITLE
added ability to set custom teamspeak name

### PR DESCRIPTION
**Pull request by vabene1111**
This addresses the ideas/problems mentioned in #1463 and #1168 by allowing the name shown in TeamSpeak (and therefore used by the plugin) to be dynamically set using the variable `TFAR_unitName`.

**When merged this pull request will:**
- Modify all scripts using the players name to use one stored in a variable instead
- not change anything for players/developers if they don't use this feature

There are 2 considerations that need to be decided before merging this:
- should `TFAR_unitName` be set in some initialization script so defaults must not be used everywhere for performance reasons ? I don't know if this matters.
- can `TFAR_spectatorName` and `TFAR_unitName` be merged in one variable ? i don't see where it is ever set to something different than the players name but i don't know if there is some technical reason.

Using a variable instead of the name directly has been tested on a large scale for the past two years on our server and has so far not revealed any problems.

### CODE REVIEW

**Comment by Reekoj** [comment]
@vabene1111 are you still active ? I think this pull request is not a draft anymore

**Comment by vabene1111** [comment]
It's been a long time since I worked on this but the feature has also been acimtivemy used all that time and is well tested. Basically I think I only set it to draft back then to decide what to do with the variables.

You can either just quickly make that change after  merging or I can look into it, whatever you want.

**Comment by vabene1111** [comment]
Cannot remove draft on mobile so either you can or I will when I am back on my PC

**Comment by Reekoj** [comment]
I have no rights on the repo i can't do anything lol, but Dedmen said he can't merge it because it's in draft status

**Comment by vabene1111** [comment]
ah ok, yea found it on GH pc version website, now it should be mergable. The code still looks fine and the change with the variables can always easily be added afterwards so i think this is ready to merge

**Comment by dedmen** [comment]
Thank you!

**Pull request merged**
