### PR TITLE
fixed formatting in README_EN.md

### PR DESCRIPTION
**Pull request by Krzmbrzl**

### CODE REVIEW

**Comment by dedmen** [comment]
Already fixed in 1.0
https://github.com/michail-nikolaev/task-force-arma-3-radio/edit/1.0/README.md

**Comment by Krzmbrzl** [comment]
But this one doesn't contain all information that are currently present on this page... Anyways - I think it doesn't hurt to have a properly formatted Readme for the old version as well :man_shrugging:

**Comment by dedmen** [comment]
Most changed will be overwritten/deleted when 1.0 is hard-merged into master.

**Comment by Krzmbrzl** [comment]
Well that doesn't hurt anyone. I put in the "effort" to format it already anyways.

But on the plus-side everyone still looking into the docs for 0.9.12 will have it properly formatted.

It's no effort for you, no additional effort for me but a gain for everyone that might look at this page before the 1.0 gets hard-merged

**Comment by dedmen** [comment]
master branch will be nuked and need to close all PR's

**Pull request closed without merging**
