### PR TITLE
typeName --> isEqualType

### PR DESCRIPTION
**Pull request by NiiRoZz**
Update of #1029 

 isEqualType much faster than typeName.

### CODE REVIEW

**Comment by michail-nikolaev** [comment]
thanks, nice PR!

**Comment by NiiRoZz** [comment]
No problem, you can PR when you want

**Comment by dedmen** [comment]
Why update? what is different from #1029 besides the whitespace changes?

**Comment by kavinsky** [comment]
resolution for this? @michail-nikolaev

**Comment by dedmen** [comment]
Discussed this with @michail-nikolaev in #1029 and decided to merge this instead of mine. But Id prefer some testing before pushing this to master. Maybe we should start a testing branch to push all PRs to that and test it first. I am able to deploy testing builds to my Arma group so we have a nice big tester base.

**Comment by dedmen** [comment]
Merged in c454cf2 but cant mark as merged because github.

**Pull request closed without merging**
