### PR TITLE
ai-hearing improvements

### PR DESCRIPTION
**Pull request by Dorbedo**
**When merged this pull request will:**
- change the remoteExec into a CBA-Event
- some of the TODO
- cleanup
- reduced the remote calling by adding some additional checks
- new setting to enable the ai abillity to detect speakers on receive (has some limitations)

### CODE REVIEW

**Comment by dedmen** [comment]
That is actually a thing remoteExec is useful for. Directly calling the command is ofcause better than CBA parsing the event PVAR and calling a script function that calls a command

**Comment by Dorbedo** [comment]
I know, but this will work even if there are strange things inside `CfgRemoteExec`.

**Comment by Dorbedo** [comment]
should be done

**Comment by dedmen** [comment]
rdy rdy rdy?

**Comment by Dorbedo** [comment]
can be merged

**Comment by dedmen** [comment]
splendid

**Pull request merged**
