### PR TITLE
Remove BWMod vehicles, fix updating base class issues (hopefully clean)

### PR DESCRIPTION
**Pull request by commy2**
see https://github.com/michail-nikolaev/task-force-arma-3-radio/pull/993

### CODE REVIEW

**Comment by michail-nikolaev** [comment]
Thanks!

**Comment by michail-nikolaev** [comment]
@commy2 which radio type now used in vehicles at BWMOD side?

**Comment by commy2** [comment]
Sorry for reading it this late. Still the ´tf_mr3000_bwmod`, but we changed our inheritance and included the config entry ourselves.

**Comment by michail-nikolaev** [comment]
@commy2 have you released updated version already?

**Comment by commy2** [comment]
Yes.

**Comment by michail-nikolaev** [comment]
@commy2 and at the moment it not works with TFAR, right? (because conflict)

**Pull request merged**
