### PR TITLE
Use new and faster isEqualType instead of comparing typeNames

### PR DESCRIPTION
**Pull request by dedmen**

### CODE REVIEW

**Comment by michail-nikolaev** [comment]
Thanks, could you add your to help section? :)

**Comment by dedmen** [comment]
That is already part of #979 should i copy it to this branch?

**Comment by michail-nikolaev** [comment]
@dedmen nope, it is fine

**Comment by michail-nikolaev** [comment]
Hm. What do you think about https://github.com/michail-nikolaev/task-force-arma-3-radio/pull/1086/files ?

**Comment by dedmen** [comment]
Seems to be the same as mine plus a ton of whitespace changes

**Comment by NiiRoZz** [comment]
You don't need to use :

isEqualType "STRING"

Only this change

**Comment by dedmen** [comment]
Yeah okey. Saving a few bytes of space.

**Comment by michail-nikolaev** [comment]
Technically both PR is equal, so my bad here. Thanks you guys for your help.

I'll probably merge https://github.com/michail-nikolaev/task-force-arma-3-radio/pull/1086 just because it has no conflict (+ add both to help section)

**Comment by dedmen** [comment]
Just merge #1086 .

**Pull request closed without merging**
