### PR TITLE
Add diary help record during briefing

### LINKED ISSUE #1473: Diary help record not available during briefing
**Arma 3 Version:** `1.92` (stable)
**CBA Version:** `3.x.x` (stable)
**Task Force Radio Version:** `1.0.318`

**Mods:**
```
- @CBA_A3
- @task_force_radio
```
**Description:**
- diary.sqf is part of TFAR_fnc_clientInit which starts after briefing 
https://github.com/michail-nikolaev/task-force-arma-3-radio/blob/4cafbc4764d9d40088c846aa0ced39a0affa2caa/addons/core/XEH_postInit.sqf#L7
I think it would be better to move it out to have diary record available during briefing.

**Steps to reproduce:**
- Run MP mission

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Editor (Multiplayer)

### PR DESCRIPTION
**Pull request by severgun**
**When merged this pull request will:**
* Fix #1473

### CODE REVIEW

**Comment by dedmen** [comment]
I also wanted to add a clientside CBA setting to disable diary stuff, this makes it much easier thanks

**Comment by severgun** [comment]
What is the point in turning help page on/off?

**Comment by dedmen** [comment]
>What is the point in turning help page on/off?

Some players prefer non-cluttered diary.

**Comment by dedmen** [comment]
Great thanks! I wanted to do that myself :D

**Comment by severgun** [comment]
I think you have enough more advanced than copy/paste stuff in TODO list.

**Pull request merged**
