### PR TITLE
Portuguese localization to stringtables.xml

### PR DESCRIPTION
**Pull request by graffo**
Added portuguese localization to Task Force Radio

### CODE REVIEW

**Comment by dedmen** [comment]
Everything on master branch will be deleted once 1.0 branch get's merged. So no point adding translations to that. Please move them to 1.0 branch.

**Comment by graffo** [comment]
Where i find the 1.0 branch?

**Comment by Dorbedo** [comment]
It's available on git too. You just need to change your active branch.
image

I'd recommend to create a new PR and close this one.

**Comment by dedmen** [comment]
>I'd recommend to create a new PR and close this one.
But I hate useless PR's.

**Comment by dedmen** [comment]
Pushed in 72ed932111e4de0b32623ba7e84ea3c11c06e476

**Pull request closed without merging**
