### PR TITLE
Fix Cycle SR/LR keybinds

### PR DESCRIPTION
**Pull request by severgun**
**When merged this pull request will:**
- title

### CODE REVIEW

**Comment by dedmen** [comment]
What do these keys even do? :D

**Comment by severgun** [comment]
When you have multiple radios in inventory you can switch them back and forth.
`CTRL+[` , `CTRL+]` for SR by default

**Comment by dedmen** [comment]
Ah. So back and forth (left and right was confusing me), I guess currently only forth worked?

**Comment by severgun** [comment]
Correct. Left and Right confuse me too, but I don't wan't to touch variables naming as much as possible.

**Comment by dedmen** [comment]
Changing the stringtable entries is no issue as they are not referenced anywhere else. And the functions already get called with "next" and "prev" arguments.

**Comment by severgun** [comment]
Like this?
Now it will conflict with https://github.com/michail-nikolaev/task-force-arma-3-radio/pull/1472

**Pull request merged**
