### PR TITLE
French translation update

### PR DESCRIPTION
**Pull request by NorXAengell**

### CODE REVIEW

**Comment by dedmen** [comment]
These translations are for the master branch. Which is deprecated.
Translations should be done on 1.0 branch.

**Comment by NorXAengell** [comment]
So i close this pullrequest and re open it in 1.0 ?

**Comment by dedmen** [comment]
Yeah.. But the stringtable files are also different in 1.0.

**Comment by NorXAengell** [comment]
I close this and redone the translation in the 1.0 branch

**Pull request closed without merging**
