### PR TITLE
Added Material icons

### PR DESCRIPTION
**Pull request by chris579**
Needs to be discussed. All icons are licensed under Apache 2.0.

### CODE REVIEW

**Comment by dedmen** [comment]
>licensed under Apache 2.0

https://github.com/michail-nikolaev/task-force-arma-3-radio/blob/master/LICENSE.md

Sooo.....

**Comment by 654wak654** [comment]
I do like the new icons but an extra clause to the license should be added stating the icons are under Apache 2.0 and not APL-SA.

Something like this maybe? https://github.com/acemod/ACE3/blob/master/LICENSE#L25-L31

**Comment by Dorbedo** [comment]
The icons are not at the same position -> they are all centered instead
This results in an ugly "jumping" of the icon upon switch

**Comment by dedmen** [comment]
We also don't need the png's if we have the .svg. The png's are just there to have the source files somewhere. I prefer svg.

**Comment by nomisum** [comment]
I could provide juggle free alignment of those. I presume SVG is not the format used by Arma though?

**Comment by dedmen** [comment]
Yes. Arma also doesn't use PNG.

**Comment by nomisum** [comment]
how about those
tfar_volume

**Comment by dedmen** [comment]
These are actually perfect XD

**Comment by nomisum** [comment]
License is "do what you want", as they are mine :D Will provide you the sources tomorrow.

**Comment by dedmen** [comment]
Can we get headset into that too?

**Pull request closed without merging**
