### PR TITLE
jpn translate

### PR DESCRIPTION
**Pull request by classicarma**
this translation is based on branch 1.0.

### CODE REVIEW

**Comment by dedmen** [comment]
Cool. Ready to merge. I just added two new strings for Half-Duplex support do you want to translate those too?

**Comment by classicarma** [comment]
@dedmen I will do it when come new words.

**Comment by dedmen** [comment]
STR_TFAR_Mod_FullDuplex and STR_TFAR_Mod_FullDuplexDescription
are now on core/stringtable.xml on the 1.0 branch

**Comment by dedmen** [comment]
Everything done?

**Comment by classicarma** [comment]
I was done and thx for marge. I'm noob of the github.

**Pull request merged**
