### PR TITLE
update dll version 0.9.7.1

### PR DESCRIPTION
**Pull request by havena**

### CODE REVIEW

**Comment by havena** [comment]
need dll recompile

**Comment by havena** [comment]
https://mega.co.nz/#!StxVVAwK!_0-HCWs2x3bzo6hLPQUC5gLX0t4CpD-L0Y54X_wsb1A
https://mega.co.nz/#!jlYUhJpb!qgiQwk8ZTfOWZQQoVNPqy4ZkujPmBQgQF7jZ_mMTiGY

**Comment by michail-nikolaev** [comment]
Thanks, but no need to update plugins currently

**Comment by michail-nikolaev** [comment]
closing because 0.9.8 already

**Pull request closed without merging**
