### PR TITLE
 Add keybinds for different speech volumes #887

### LINKED ISSUE #887: Add keybinds for different speech volumes
It would be nice if we could map direct speech to keys with a certain volume, e.g. a yelling button such as right ctrl and still use my normal push to talk as normal.

### PR DESCRIPTION
**Pull request by ACyprus**
Adds a set of 'modifier' keys that allow a transient change in speaking volume whilst they are held down. 

I've introduced one for yelling and one for whispering.

There are no default keybinds.

Holding down a modifier key while transmitting will change the speaking volume and display a relevant hint.

Releasing the modifier will remove the hint and reset the speaking volume to the previous setting.

NOTE: the key binds in configuration are currently called "Yelling Modifier" and "Whispering Modifier" - only because I couldn't think of a better phrase. I am open to suggestions - perhaps something that would place them next to "Change Speaking Volume" in the list.

I've tested this on dedicated and works well. Could do with some 'third party' testing.

Closes #887

### CODE REVIEW

**Comment by ACyprus** [comment]
PS: should I make this feature available to curator players?

**Comment by michail-nikolaev** [comment]
Sorry - on vacation now + lost my dig - will review probably tommorow

**Comment by ACyprus** [comment]
Thanks, No rush. Enjoy your vacation!

PS - when you're back, if you could let me know how I might initiate direct speech from the plugin then I can change these from just modifier keys to actual send speech keys. (Unless you meant you need to update the plugin first)

**Comment by dedmen** [comment]
Can you please implement use of the "param" command into your onSpeakVolumeModifierPressed/Released functions?

like in #990

**Comment by dedmen** [comment]
just for reference...... It doesn't work correctly when you switch between the modifier keys as fast as you can...

**Pull request merged**
