### PR TITLE
bwc for tf_guer_radio_code

### PR DESCRIPTION
**Pull request by Dorbedo**
`tf_guer_radio_code` should stay for this version instead of `tf_independent_radio_code`

### CODE REVIEW

**Comment by dedmen** [comment]
You are missing one.

**Comment by dedmen** [comment]
https://github.com/michail-nikolaev/task-force-arma-3-radio/blob/97583dc6a8a42c958460d3b2d7eca57469fe7757/arma3/%40task_force_radio/addons/task_force_radio/functions/fn_ClientInit.sqf#L19 That was maybe the reason why it was changed. Not sure

https://github.com/michail-nikolaev/task-force-arma-3-radio/blob/47d03aa686d96169fe13a5c4cfe139b081031265/arma3/%40task_force_radio/addons/task_force_radio/functions/fn_initialiseBaseModule.sqf#L66 There. Is that code still somewhere?

**Comment by dedmen** [comment]
guer was used because `independent` stringified as GUER in A2. But I think that changed in A3 and I think that stringification caused some problems. So I probably changed it so it matches

**Comment by Dorbedo** [comment]
I'll take a deeper look another time, so no merge for now.

**Comment by dedmen** [comment]
Keep in mind that I got very little sleep.

**Comment by Dorbedo** [comment]
alright, it's reverted and changed into supporting of the old value

**Comment by dedmen** [comment]
Get sleep o7

**Comment by Dorbedo** [comment]
rdy to merge

**Pull request merged**
