### PR TITLE
TS-Channelname changed into CBA_settings

### PR DESCRIPTION
**Pull request by Dorbedo**
- remove the 3DEN Channelsetting
- add the CBA-Setting for Channelname and PW
- needs next CBA

### CODE REVIEW

**Comment by dedmen** [comment]
waiting for password masking thingy in CBA.

**Comment by dedmen** [comment]
Can you add https://github.com/CBATeam/CBA_A3/pull/802/files ?
Then this can be merged-

**Comment by Dorbedo** [comment]
It's done, just need cba 3.5.1 to be released

**Comment by dedmen** [comment]
Does it break if we merge it before CBA release?

**Comment by Dorbedo** [comment]
Yes, it would break.

**Comment by dedmen** [comment]
https://github.com/CBATeam/CBA_A3/blob/release/addons/settings/fnc_init.sqf#L91
That looks like they just use the first array element though.. Which would be `""` which would work just fine?

**Pull request merged**
