### PR TITLE
Use the new param command

### PR DESCRIPTION
**Pull request by kavinsky**
Added basic support for `params`, most function parameters now use that command

### CODE REVIEW

**Comment by kavinsky** [comment]
OK, now starts without error on rpt, ill test with my unit in the next weeks.

**Comment by michail-nikolaev** [comment]
Nice :)

**Comment by michail-nikolaev** [comment]
@kavinsky so, merge now?

**Comment by kavinsky** [comment]
@michail-nikolaev im back from holidays, ill check it this days.

**Comment by michail-nikolaev** [comment]
@kavinsky thanks!

**Comment by dedmen** [comment]
Please merge master or 1.0 into you PR. Then Squash and merge if you think this is done. Already changed merge target to 1.0 branch.

**Comment by dedmen** [comment]
Remember to notify #954 that he should merge with 1.0 branch after this is merged.

**Pull request merged**
